fn main() {
    // Descobre o SO de destino (não o do host!)
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();

    // Só embute ícone quando o TARGET for Windows (.exe)
    if target_os == "windows" {
        let mut res = winres::WindowsResource::new();
        res.set_icon("app.ico"); // ajuste o caminho do seu .ico
        // Não derruba builds de outras plataformas caso falhe por algum motivo
        if let Err(e) = res.compile() {
            eprintln!("winres falhou: {e}");
        }
    }

    let cfg = slint_build::CompilerConfiguration::new().with_style("cosmic-dark".into());
    slint_build::compile_with_config("ui/app.slint", cfg).expect("Failed to compile Slint UI");

    // Adiciona dependências: serde = { version = "1", features = ["derive"] }, serde_json = "1" em [build-dependencies] no Cargo.toml
    // Gera lista de Pokémon a partir do JSON
    let json_path = "data_json/pokemons.json";
    let json = std::fs::read_to_string(json_path).expect("failed to read JSON");
    let pokemons: serde_json::Value = serde_json::from_str(&json).expect("failed to parse JSON");

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs\n");
    out.push_str("#[derive(Copy, Clone)]\n");
    out.push_str("pub struct Pokemon {\n");
    out.push_str("    pub species_id: u32,\n");
    out.push_str("    pub name: &'static str,\n");
    out.push_str("    pub hp: u16,\n");
    out.push_str("    pub atk: u16,\n");
    out.push_str("    pub def: u16,\n");
    out.push_str("    pub sp_atk: u16,\n");
    out.push_str("    pub sp_def: u16,\n");
    out.push_str("    pub speed: u16,\n");
    out.push_str("    pub ability1: &'static str,\n");
    out.push_str("    pub ability2: &'static str,\n");
    out.push_str("    pub hidden: &'static str,\n");
    out.push_str("    pub weight_kg: f64,\n");
    out.push_str("    pub height_m: f64,\n");
    out.push_str("    pub color: &'static str,\n");
    out.push_str("    pub evolutions: &'static [Evolution],\n");
    out.push_str("}\n");
    out.push_str("#[derive(Copy, Clone)]\n");
    out.push_str("pub struct Evolution {\n    pub to: u32,\n    pub name: &'static str,\n    pub method: &'static str,\n}\n");
    out.push_str("pub const POKEMON_LIST: &[Pokemon] = &[\n");

    for poke in pokemons.as_array().expect("JSON root is not array") {
        let empty_evolutions = Vec::new();
        let evolutions = poke.get("evolutions").and_then(|ev| ev.as_array()).unwrap_or(&empty_evolutions);
        let mut evo_str = String::from("&[]");
        if !evolutions.is_empty() {
            evo_str = String::from("&[");
            for evo in evolutions {
                let to = evo.get("to").and_then(|v| v.as_u64()).unwrap_or(0);
                let name = evo.get("name").and_then(|v| v.as_str()).unwrap_or("");
                let method = evo.get("method").and_then(|v| v.as_str()).unwrap_or("");
                evo_str.push_str(&format!("Evolution {{ to: {}, name: \"{}\", method: \"{}\" }},", to, name, method));
            }
            evo_str.push_str("]");
        }
        let weight = poke.get("weight_kg").and_then(|v| v.as_f64()).unwrap_or(0.0);
        let height = poke.get("height_m").and_then(|v| v.as_f64()).unwrap_or(0.0);
        out.push_str(&format!(
            "    Pokemon {{ species_id: {}, name: \"{}\", hp: {}, atk: {}, def: {}, sp_atk: {}, sp_def: {}, speed: {}, ability1: \"{}\", ability2: \"{}\", hidden: \"{}\", weight_kg: {:.1}, height_m: {:.1}, color: \"{}\", evolutions: {} }},\n",
            poke.get("species_id").and_then(|v| v.as_u64()).unwrap_or(0),
            poke.get("name").and_then(|v| v.as_str()).unwrap_or("").replace('"', "\\\""),
            poke.get("HP").and_then(|v| v.as_u64()).unwrap_or(0),
            poke.get("Atk").and_then(|v| v.as_u64()).unwrap_or(0),
            poke.get("Def").and_then(|v| v.as_u64()).unwrap_or(0),
            poke.get("SpAtk").and_then(|v| v.as_u64()).unwrap_or(0),
            poke.get("SpDef").and_then(|v| v.as_u64()).unwrap_or(0),
            poke.get("Speed").and_then(|v| v.as_u64()).unwrap_or(0),
            poke.get("ability1").and_then(|v| v.as_str()).unwrap_or("").replace('"', "\\\""),
            poke.get("ability2").and_then(|v| v.as_str()).unwrap_or("").replace('"', "\\\""),
            poke.get("hidden").and_then(|v| v.as_str()).unwrap_or("").replace('"', "\\\""),
            weight,
            height,
            poke.get("color").and_then(|v| v.as_str()).unwrap_or("").replace('"', "\\\""),
            evo_str
        ));
    }
    out.push_str("];");

    // gera em OUT_DIR
    let out_dir = std::env::var("OUT_DIR").unwrap();
    std::fs::write(std::path::Path::new(&out_dir).join("pokemon_list.rs"), out).unwrap();
}
